spring.application.name=IS_TermWork_UNO

spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=s367656
spring.datasource.password=SZOigcMO1pXR92lE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:scripts/*

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.config.import=optional:file:./config/game-config.yml
