DROP TYPE IF EXISTS type_of_card CASCADE;
DROP TYPE IF EXISTS color_of_card CASCADE;

DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS GameRoom CASCADE;
DROP TABLE IF EXISTS Game CASCADE;
DROP TABLE IF EXISTS GameScore CASCADE;
DROP TABLE IF EXISTS Card CASCADE;
DROP TABLE IF EXISTS Deck CASCADE;
DROP TABLE IF EXISTS Statistics CASCADE;
DROP TABLE IF EXISTS Achievement CASCADE;
DROP TABLE IF EXISTS UserAchievement CASCADE;
DROP TABLE IF EXISTS Message CASCADE;
